In [1]:
import os

In [2]:
print(os.listdir())

['.ipynb_checkpoints', 'Social_Network_Ads.csv', 'svm.ipynb']


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_csv('Social_Network_Ads.csv')

In [5]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
X=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [10]:
 X_test

array([[    34,  43000],
       [    34, 112000],
       [    35,  58000],
       [    21,  68000],
       [    29, 148000],
       [    41,  60000],
       [    26, 118000],
       [    35, 147000],
       [    35,  38000],
       [    26,  15000],
       [    35,  72000],
       [    40,  75000],
       [    53,  82000],
       [    48, 141000],
       [    27,  84000],
       [    22,  81000],
       [    39,  71000],
       [    24,  23000],
       [    59,  83000],
       [    39,  79000],
       [    49,  74000],
       [    47,  25000],
       [    52,  90000],
       [    36,  50000],
       [    27,  57000],
       [    46,  59000],
       [    27,  96000],
       [    50,  36000],
       [    37,  70000],
       [    33,  69000],
       [    59,  42000],
       [    43, 129000],
       [    41,  87000],
       [    42,  65000],
       [    24,  32000],
       [    46,  82000],
       [    31,  76000],
       [    41,  52000],
       [    45,  22000],
       [    21,  16000],


In [11]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [12]:
sc = StandardScaler()

In [13]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_test

array([[-3.63736377e-01, -7.93123138e-01],
       [-3.63736377e-01,  1.23327803e+00],
       [-2.68564144e-01, -3.52601145e-01],
       [-1.60097540e+00, -5.89198165e-02],
       [-8.39597541e-01,  2.29053081e+00],
       [ 3.02469252e-01, -2.93864879e-01],
       [-1.12511424e+00,  1.40948683e+00],
       [-2.68564144e-01,  2.26116268e+00],
       [-2.68564144e-01, -9.39963802e-01],
       [-1.12511424e+00, -1.61543086e+00],
       [-2.68564144e-01,  5.85527148e-02],
       [ 2.07297019e-01,  1.46657113e-01],
       [ 1.44453605e+00,  3.52234043e-01],
       [ 9.68674881e-01,  2.08495388e+00],
       [-1.02994201e+00,  4.10970309e-01],
       [-1.50580317e+00,  3.22865910e-01],
       [ 1.12124787e-01,  2.91845820e-02],
       [-1.31545870e+00, -1.38048579e+00],
       [ 2.01556944e+00,  3.81602176e-01],
       [ 1.12124787e-01,  2.64129645e-01],
       [ 1.06384711e+00,  1.17288981e-01],
       [ 8.73502649e-01, -1.32174953e+00],
       [ 1.34936381e+00,  5.87179106e-01],
       [-1.

In [15]:
from sklearn.svm import SVC

In [16]:
classifier = SVC(kernel='linear')
classifier.fit(X_train,y_train.ravel())

SVC(kernel='linear')

In [17]:
y_predictor = classifier.predict(X_test)

In [18]:
y_predictor

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
#creating confusion matrix
from sklearn.metrics import confusion_matrix

In [20]:
errors = confusion_matrix(y_test,y_predictor)

In [21]:
errors

array([[49,  8],
       [ 8, 15]], dtype=int64)