In [1]:
#check the correcr directory first
import os
print(os.listdir())

['.ipynb_checkpoints', '01-data preprocessing.ipynb', 'CleanupData.csv']


In [2]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#plotting is visible
%matplotlib inline


In [3]:
data = pd.read_csv('CleanupData.csv')

In [4]:
data

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [5]:
data.head()

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   State             10 non-null     object 
 1   Age               9 non-null      float64
 2   Pocket Money      9 non-null      float64
 3   Course Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [31]:
#get your independent and dependent matrix out of the dataset
X = data.iloc[:,:-1].values

In [32]:
#matrix of independent variables
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [33]:
#matrix of dependent variables
y=data.iloc[:,3].values

In [34]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [42]:
#handling missing values
from sklearn.impute import SimpleImputer


In [47]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [52]:
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])


In [53]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

# handle categotrical data in our data


In [54]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,0]= labelencoder_X.fit_transform(X[:,0])
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [72]:
#create diummy matrix for categorical dataset
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categories='auto')
X=onehotencoder.fit_transform(X).toarray()
np.set_printoptions(suppress=True)
X

array([[0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 1., 1., 0.]])

In [64]:
X


array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [65]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [73]:
#handling y matrix
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [76]:
#prepare test and training dataset
#split our data into 2 parts...one will be training and other will be test data
from sklearn.model_selection import train_test_split

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [81]:
X_train

array([[0., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.]])

In [82]:
y_train


array([1, 1, 0, 1, 0, 0, 1, 0])

In [83]:
#feature scaling
#standard deviation or normalization --> most used methods in feature scaling
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)

In [84]:
X_train

array([[-0.77459667,  0.77459667,  0.77459667, ...,  0.37796447,
         0.37796447, -0.37796447],
       [ 1.29099445, -1.29099445, -1.29099445, ...,  0.37796447,
         0.37796447, -0.37796447],
       [ 1.29099445, -1.29099445, -1.29099445, ..., -2.64575131,
        -2.64575131,  2.64575131],
       ...,
       [-0.77459667,  0.77459667,  0.77459667, ...,  0.37796447,
         0.37796447, -0.37796447],
       [-0.77459667,  0.77459667,  0.77459667, ...,  0.37796447,
         0.37796447, -0.37796447],
       [-0.77459667,  0.77459667,  0.77459667, ...,  0.37796447,
         0.37796447, -0.37796447]])