In [1]:
import numpy as np

exercise file for numpy


In [2]:
mylist=[1,2,3,4,5]

In [3]:
mylist

[1, 2, 3, 4, 5]

In [4]:
import numpy as np

In [6]:
my1darray=np.array(mylist)

In [7]:
my1darray

array([1, 2, 3, 4, 5])

In [8]:
my2list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [9]:
my2dArray = np.array(my2list)

In [10]:
my2dArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
np.arange(0, 100 ,2) #to put conditions

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
np.zeros((4,4))  #to pass a zero matrix as per my choice

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#MORE WORKS WITH NUMPY ARRAYS

In [19]:
np.linspace(0,5, 15) #linear distribution

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

np.identity()  =>this function handles the identity matrix

In [20]:
 np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5,5)

array([[0.60177798, 0.54926518, 0.3370614 , 0.79446115, 0.80845216],
       [0.15023634, 0.14562347, 0.23942519, 0.16979502, 0.86428594],
       [0.32405063, 0.5969035 , 0.08094744, 0.42483698, 0.04353566],
       [0.7694245 , 0.40481968, 0.89350443, 0.02422983, 0.67903824],
       [0.83683771, 0.8691154 , 0.99465004, 0.96813997, 0.86008282]])

In [24]:
np.random.randn(5,5) #for unifrom distribution

array([[-1.39938058, -0.27520289, -0.0284326 , -1.13141841, -0.95774785],
       [-0.86558379,  1.88420306,  0.03190963, -1.30811785, -0.68377864],
       [-0.07356401, -1.4065555 , -0.33555054,  0.3400202 , -0.01506066],
       [ 1.58458525,  0.99312118, -0.03930728, -0.68321565, -0.55212938],
       [ 0.59162437,  0.35573706, -0.48033392,  0.95958682,  1.23602132]])

In [26]:
np.random.randint(1, 50) #gives a random number between 2 limits

49

In [27]:
myNum = np.arange(25)

In [29]:
myNum #the last digit won't be printed

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
myReshaped = myNum.reshape(5,5) #for converting lists

In [33]:
myReshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
myReshaped.dtype #gives the datatype 

dtype('int32')