#Intermediate Stuffs with numpy

In [1]:
import numpy as np

In [2]:
myArray = np.arange(10,21)

In [3]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
myArray[0]

10

In [6]:
myArray[0:4] #slicing

array([10, 11, 12, 13])

In [7]:
partarray = myArray[:4]

In [8]:
partarray

array([10, 11, 12, 13])

In [9]:
partarray[:] = 50   #USING A COLON GIVES ALL THE ELEMENTS A VALUE

In [10]:
copyarray = myArray.copy()

In [12]:
copyarray[:]=200

In [13]:
copyarray

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [14]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

#part 2 

In [15]:
my2darray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
my2darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
my2darray[2][1]       #the first one is for the rows an the 2nd square bracket is for the columns

8

In [18]:
my2darray[:2, 1:]

array([[2, 3],
       [5, 6]])